# 本文件仅供本机运行，已被 .gitignore 忽略。

[run]
product = vol
rates = 1,10,50
duration_seconds = 60
storages = none
max_workers = 1000
output = results
exclude_first_from_mean = true

[product.aliyun]
name = 阿里云
api_key =e2b_9f30d752ee5e30208fb225989108a6f1bdb07f61
api_key_env = E2B_API_KEY
api_url = https://api.cn-beijing.e2b.fc.aliyuncs.com
domain = cn-beijing.e2b.fc.aliyuncs.com
template = code-interpreter-v1
sandbox_timeout = 60
vpc_config_json =
oss_config_json =
role_arn =
file_metadata_key =
file_config_json =
extra_metadata_json =

[product.vol]
name = 字节
api_key = e2b_d550294265280d499894795ceca291c906cac9852e606ed7f423d909627dc01f
api_key_env = VOL_E2B_API_KEY
api_url = https://api.vefaas-e2b.sandbox-cn-beijing.volcapig.com
domain = vefaas-e2b.sandbox-cn-beijing.volcapig.com
template = zhbatkbe
sandbox_timeout = 60
vpc_config_json =
oss_config_json =
role_arn =
file_metadata_key =
file_config_json =
extra_metadata_json =
